create procedure sp_editar_padrao
@ID INT,
@PRINTER_IP VARCHAR(15),
@DESC_PRINTER VARCHAR(100),
@IS_DEFAULT BIT
as

UPDATE [dbo].[CONFIG_PRINTER]
   SET [PRINTER_IP] = @PRINTER_IP
      ,[DESC_PRINTER] = @DESC_PRINTER
      ,[IS_DEFAULT] = @IS_DEFAULT
 WHERE ID = @ID
GO


